#!/usr/bin/env bash
# =============================================================================
# stage_data.sh — hash and index the pre-staged read-only data volume.
# =============================================================================
#   ops/stage_data.sh [--check] [DIR]
#
# Walks the data directory (default harness/data/), writes manifest.sha256 and
# INDEX.md, and warns about any source directory missing provenance. Run it
# after every change to the volume: a stale INDEX.md means the agent does not
# know about data you staged.
#
#   --check   verify files still match manifest.sha256 and change nothing.
#             ops/provision-box.sh runs it after the copy to the box,
#             ops/run.sh immediately before launch, and ops/collect.sh after
#             the run — so "the bytes the run read are the bytes you staged"
#             is a verified fact rather than an assumption.
#   DIR       the volume to work on (default: harness/data; on the box,
#             wherever CRUX_DATA_DIR in harness/.env points).
#
# The directory is mounted read-only at /data in the container when
# CRUX_DATA_DIR is set (data/README.md says what belongs there — only what the
# agent cannot fetch for itself).
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECK=0
DATA=""
for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    -h|--help) echo "usage: ops/stage_data.sh [--check] [DIR]" >&2; exit 1 ;;
    *) [ -z "$DATA" ] || { echo "usage: ops/stage_data.sh [--check] [DIR]" >&2; exit 1; }; DATA="$arg" ;;
  esac
done
[ -n "$DATA" ] || DATA="$(cd "$HERE/.." && pwd)/data"
[ -d "$DATA" ] || { echo "FATAL: $DATA does not exist"; exit 1; }
DATA="$(cd "$DATA" && pwd)"
MANIFEST="$DATA/manifest.sha256"
INDEX="$DATA/INDEX.md"

# Portable sha256: coreutils on Linux, BSD shasum on macOS.
if command -v sha256sum >/dev/null 2>&1; then
  SHA() { sha256sum "$@"; }
  SHACHECK() { sha256sum -c --quiet "$@"; }
elif command -v shasum >/dev/null 2>&1; then
  SHA() { shasum -a 256 "$@"; }
  SHACHECK() { shasum -a 256 -c --status "$@"; }
else
  echo "FATAL: no sha256sum or shasum on PATH"; exit 1
fi

# Everything except the generated/tracked metadata itself.
find_payload() {
  find . -type f \
    ! -name 'manifest.sha256' ! -name 'INDEX.md' \
    ! -name 'README.md' ! -name '.gitignore' ! -name '.DS_Store' \
    | sed 's|^\./||' | LC_ALL=C sort
}

cd "$DATA"

if [ "$CHECK" = "1" ]; then
  [ -f "$MANIFEST" ] || { echo "FATAL: no manifest.sha256 in $DATA — run without --check first"; exit 1; }
  if SHACHECK "$MANIFEST"; then
    echo "✔ all $(grep -c . "$MANIFEST") staged files match manifest.sha256"
    exit 0
  fi
  echo "✘ staged data does NOT match manifest.sha256 — files changed since staging."
  echo "  Investigate before launching: the manifest is the record of what the run read."
  exit 1
fi

N_FILES=0
BYTES=0
MISSING_PROV=""

# ── Hash everything ───────────────────────────────────────────────────────
: > "$MANIFEST"
while IFS= read -r f; do
  [ -n "$f" ] || continue
  SHA "$f" >> "$MANIFEST"
  N_FILES=$((N_FILES + 1))
  SZ=$(wc -c < "$f" | tr -d ' ')
  BYTES=$((BYTES + SZ))
done < <(find_payload)

human() { # bytes -> human
  awk -v b="$1" 'BEGIN{s="B KB MB GB TB"; split(s,u," "); i=1;
    while (b>=1024 && i<5){b/=1024;i++} printf (i==1 ? "%d %s" : "%.1f %s"), b, u[i]}'
}

# ── Regenerate the agent-facing index ─────────────────────────────────────
{
  echo "# Pre-staged data (\`/data\`, read-only)"
  echo
  echo "Generated by \`ops/stage_data.sh\` — do not edit by hand."
  echo
  echo "This volume is mounted read-only. Its contents are hashed in"
  echo "\`manifest.sha256\`, which is the record of exactly what this run started"
  echo "from. Copy or decompress into your workspace rather than trying to write"
  echo "here, and cite the provenance below when a dataset enters the paper."
  echo
  echo "**$N_FILES file(s), $(human "$BYTES") total.**"
  echo

  FOUND_ANY=0
  for d in */; do
    [ -d "$d" ] || continue
    FOUND_ANY=1
    name="${d%/}"
    echo "## \`$name\`"
    echo

    if [ -f "$d/SOURCE.txt" ]; then
      echo '```'
      sed 's/[[:space:]]*$//' "$d/SOURCE.txt"
      echo '```'
    else
      echo "_No \`SOURCE.txt\` — provenance unrecorded. Treat the origin and vintage of"
      echo "these files as unknown, and say so if they enter the paper._"
      MISSING_PROV="$MISSING_PROV $name"
    fi
    echo

    echo "| File | Size |"
    echo "|---|---|"
    find "$d" -type f ! -name 'SOURCE.txt' ! -name '.DS_Store' \
      | sed 's|^\./||' | LC_ALL=C sort \
      | while IFS= read -r f; do
          echo "| \`/data/$f\` | $(human "$(wc -c < "$f" | tr -d ' ')") |"
        done
    echo
  done

  if [ "$FOUND_ANY" = "0" ]; then
    echo "_Nothing staged yet. See \`README.md\` in this directory for the layout._"
  fi
} > "$INDEX"

# ── Report ────────────────────────────────────────────────────────────────
echo "✔ hashed $N_FILES file(s), $(human "$BYTES") → $MANIFEST"
echo "✔ wrote $INDEX"
if [ -n "$MISSING_PROV" ]; then
  echo "⚠ missing SOURCE.txt in:$MISSING_PROV"
  echo "  Add one per directory (URL, retrieval date, vintage, quirks). Provenance"
  echo "  that exists only in your head is provenance the paper cannot cite."
fi
if [ "$N_FILES" = "0" ]; then
  echo "⚠ nothing staged — /data will be an empty read-only mount (or leave CRUX_DATA_DIR unset for none)."
fi
